all:
  children:
    test:
      hosts:
        suse:
          ansible_host: 10.128.0.4
          ansible_user: moi
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519.pub
        dockcompose:
          ansible_host: 10.128.0.3
          ansible_user: moi
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519.pub
